DROP DATABASE bamazon_db;

CREATE DATABASE bamazon_db;

USE bamazon_db;

CREATE TABLE products(
id INT NOT NULL AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(100) NOT NULL,
DEPARTMENT_NAME VARCHAR(100) NOT NULL, 
PRICE INT default 15,
STOCK_QUANTITY INT default 3,
PRIMARY KEY(ID)
);

INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("HAT", "CLOTHING", 15, 4);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("SHIRT", "CLOTHING", 20, 10);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("PANTS", "CLOTHING", 25, 15);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("SHOES", "CLOTHING", 30, 20);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("TOASTER", "ELECTRONICS", 45, 4);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("MICROWAVE", "ELECTRONICS", 55, 10);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("BLENDER", "ELECTRONICS", 35, 15);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("BEER", "DRINKS", 15, 20);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("SODA", "DRINKS", 10, 15);
INSERT INTO products (PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) VALUES ("WATER", "DRINKS", 5, 4);

select * from products;

